### ISSUE TITLE
Consistently use Widget vs Scarpe::Widget, etc (for all the various Scarpe classes)

### ISSUE THREAD

**Issue by noahgibbs** [scarpe-team/scarpe#127]
Right now we use various module names sometimes but not always. Should we always refer to parent classes/modules all the way from the root (e.g. ::Scarpe::DisplayService::Linkable)? Should we always use the shortest that works (e.g. DisplayService::Linkable when referred to from a Scarpe Widget, and just "Widget" from inside a Scarpe::Button?)

Pick a style, make sure it's applied consistently across the codebase. This is *not* currently meaningful, in the sense that we're using both in some way that expresses something about the code. Right now it's just messy -- there are differences in what we type, but they don't indicate anything about the underlying problem. So either fix is fine.

**Comment by msaini0r** [comment]
@noahgibbs trying to setup this project, facing a issue `An error occurred while installing webview_ruby (0.1.1), and Bundler cannot continue.` Any idea how to resolve it. 

![Screenshot 2023-03-05 183502](https://user-images.githubusercontent.com/87536360/222962205-8952ab63-dbb8-443d-a470-d5487fd4d912.png)

**Comment by noahgibbs** [comment]
That *looks* like what happens when Webview needs something for its build and can't get it -- a library or similar. Could you check the build file it recommends, gem_make.out, and see what it says in that file, especially near the bottom?

**Comment by msaini0r** [comment]
@noahgibbs tried opening the gem_make.out file and it showing

```
current directory: /home/msaini0r/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/webview_ruby-0.1.1/ext
/home/msaini0r/.rbenv/versions/3.2.0/bin/ruby -I/home/msaini0r/.rbenv/versions/3.2.0/lib/ruby/3.2.0 -rrubygems /home/msaini0r/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/exe/rake RUBYARCHDIR\=/home/msaini0r/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/extensions/x86_64-linux/3.2.0/webview_ruby-0.1.1 RUBYLIBDIR\=/home/msaini0r/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/extensions/x86_64-linux/3.2.0/webview_ruby-0.1.1
Ignoring debug-1.7.1 because its extensions are not built. Try: gem pristine debug --version 1.7.1
Ignoring rbs-2.8.2 because its extensions are not built. Try: gem pristine rbs --version 2.8.2
g++ -fexceptions -O -fno-omit-frame-pointer -fno-strict-aliasing -std=c++11 -fexceptions -O -fno-omit-frame-pointer -fno-strict-aliasing -fPIC   -o x86_64-linux/webview/webview.o -c ./webview/webview.cpp
mkdir -p x86_64-linux/webview
In file included from ./webview/webview.cpp:1:
./webview/webview.h:439:10: fatal error: JavaScriptCore/JavaScript.h: No such file or directory
  439 | #include <JavaScriptCore/JavaScript.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
rake aborted!
Command failed with status (1): [g++ -fexceptions -O -fno-omit-frame-pointe...]

Tasks: TOP => default => x86_64-linux/libwebview-ext.so => x86_64-linux/webview/webview.o
(See full trace by running task with --trace)

rake failed, exit code 1

```

**Comment by noahgibbs** [comment]
That looks like it's looking for Webkit and not finding it. The gem it's complaining about is Marco's bindings for Webview (https://github.com/Maaarcocr/webview_ruby), but may require Webview stuff to be installed (https://github.com/webview/webview). Can you go to that second link and make sure the appropriate stuff is installed for your operating system?

**Comment by msaini0r** [comment]
@noahgibbs I tried it but getting the same error.

**Comment by noahgibbs** [comment]
At this point, I feel like the Lacci PR handles this nicely. Closing.
