### ISSUE TITLE
Remove outdated --no-shoes option from exe/scarpe

### ISSUE THREAD

**Issue by noahgibbs** [scarpe-team/scarpe#129]
We always want to use Shoes, I'm pretty sure. At this point we've talked it through, and it's not just that Shoes should be the default -- it should be available universally, even if Scarpe is (effectively) an alias for it.

The option should go away in exe/scarpe, so the Shoes alias should *always* be defined. And it should be defined in the library, not just through exe/scarpe.

**Comment by rohit9625** [comment]
I want to work on this issue, can you please help me understand that what it is about?

**Comment by noahgibbs** [comment]
I think @gintama91 ***just*** merged a PR fixing this one, so I think we should close it.
