### ISSUE TITLE
Webview tests should notice a crash (error exit) and complain

### ISSUE THREAD

**Issue by noahgibbs** [scarpe-team/scarpe#134]
Segfault shouldn't count as okay for :exit_immediately (see test_helper.rb).

In general we should figure out how to detect the difference between "exited" and "crashed" so that we notice crashes. Right now in test_helper, if it returns a value and then crashes, that's considered just fine. It happens frequently when I'm developing.

That's because we only check for the returned value. We ignore the process's error status on exit completely.

**Comment by gintama91** [comment]
checking the exit status would suffice this? or should we explicitly check for segfault like adding signal handlers? @noahgibbs

**Comment by noahgibbs** [comment]
Exit status would be great. I don't think we need explicit handlers (yet?)

**Comment by noahgibbs** [comment]
Now fixed!
