### ISSUE TITLE
[Secondary DSL] parents and children

### ISSUE THREAD

**Issue by Schwad** [scarpe-team/scarpe#16]
### Tasklist
- [ ] elements should have access to their parents and children. e.g. `para 'hi', link("delete) { x.parent.remove }`

**Comment by noahgibbs** [comment]
We track these things in widget - so this may only be a very small change to the existing DSL. We *should* see what existing Shoes uses for this and make sure we match it, which may be most of the work for this feature.

**Comment by Schwad** [comment]
See full thread here: https://discord.com/channels/1072538177321058377/1072538178659024898/1091676889376112700

We are revisiting development for Scarpe to be example driven. For example, PRs that pass "x" example for "y" display service. (Or general issues like architecture, bugfixes, documentation, etc.)

Afterwards, when we have them passing, we will drill harder into the API design to make sure we have parity to pass HacketyHack. 

That means we will not be tracking with issues like this for now. Feel free to leave feedback in the discord.
