### ISSUE TITLE
GlimmerLibUI examples passing CI check

### ISSUE THREAD

**Issue by Schwad** [scarpe-team/scarpe#165]
Not for yet, but when I have 20-30+ GlimmerLibUI examples passing it might be worth finding a way to add it to the CI crash checks. 

There was a change in the last week that didn't break Webview but did Glimmer. It was an easy fix but something we may want to track. 

Again, not a priority for now but something I want to make note of and track

**Comment by noahgibbs** [comment]
At this point I don't think we want the GlimmerLibUI stuff to expand in its current form, or to get scarpe-team/scarpe CI checks. We'd want to extract it into a gem if it grew. So I think this can be  closed. @schwad, agree or no?

**Comment by noahgibbs** [comment]
Okay, I'll close this. Feel free to reopen if appropriate.
