### ISSUE TITLE
Hackety-Track

### ISSUE THREAD

**Issue by noahgibbs** [scarpe-team/scarpe#166]
How close are we to running Hackety-Hack? I cloned the repo and checked.

We don't have a "shoes" executable (like the scarpe one), but we can still use some trickery to get it all working:

~~~
> ruby -I. ../scarpe/exe/scarpe --dev h-ety-h.rb
/Users/noah/src/hacketyhack/lib/dev/init.rb:48:in `<top (required)>': undefined method `font' for main:Object (NoMethodError)

font "#{HH::FONTS}/Lacuna.ttf"
^^^^
~~~

Looks like Shoes has a "font" method to load in a new font (I don't see it in Hackety-Hack, I *think* it's Shoes), and we dont currently support it. So that's our current first obstacle to running Hackety-Hack.

**Comment by noahgibbs** [comment]
@gintama91 recently added support for the font method and local fonts. So the problem of long standing with Hackety-Hack *may* be finished, and we can move onto the next problem.

**Comment by noahgibbs** [comment]
Huh. Hackety-Hack appears to expect font to be usable even outside the Shoes::App instance. I guess that means it's supposed to be defined on Kernel (as are a number of other Shoes methods.)

**Comment by gintama91** [comment]
hm.. so if we take alert it  should spin up its own app?

**Comment by noahgibbs** [comment]
Nope. It's a little freestanding widget thing mostly separate from your app. Kind of like how alert works in JS. It can also be used even if you never calls Shoes.app.

Old Shoes also has some other dialogs like that -- enter text, pick a color, etc.

**Comment by noahgibbs** [comment]
For more details, search "builtin" on Shoes API Wiki page: https://github.com/scarpe-team/scarpe/wiki/ShoesAPI.md

**Comment by gintama91** [comment]
this is probably ugly but cant we just do something like

```
def methodname
  Shoes.app do
    our-present-method
  end
end
```

and now we can call this directly ?

**Comment by noahgibbs** [comment]
What I'm planning to do is to take methods on the builtin list, put them in a module (called something like Shoes::Builtins) and then include that module from Kernel. Keeps 'em organised, means they're appropriately callable.

A top-level def (what you show there) is nearly the same and would probably work fine. But when it's easy, I'm trying hard to do it how Shoes does.

**Comment by noahgibbs** [comment]
Incidentally, do you already know how to look through the Shoes3 and Shoes4 code? Would you like to schedule a call and we'll walk through it a bit?

They're very different from each other, but both have a lot of really useful info for this.

**Comment by noahgibbs** [comment]
Also: I have a PR I'm working on which will do the builtins thing for some of these, so maybe don't work on this in the next few days :-)

**Comment by noahgibbs** [comment]
PR #410 should let us get slightly farther with this. Worth testing again to see the current obstacle after that gets merged.

**Comment by noahgibbs** [comment]
When using the branch from PR #410 I no longer get the font error. Instead I get a circular reference in the Cucumber gem, which seems mostly unused. I removed it, and then get an error that File.exists? is no longer a thing (true) in the ancient version of rspec-core Hackety is using.

There are basically no tests for Hackety, so I commented that out too. And then figured out that just running with --dev doesn't necessarily use local-dev versions of Lacci and Scarpe-Components. It probably should, I'll go fix that.

Updated the Gemfile to use local everything, and got to the next real problem: no support for Shoes::Widget. So that's our next obstacle to running Hackety.

**Comment by noahgibbs** [comment]
Huh. Also, Hackety-Hack has basically a LOGO implementation as a Shoes widget. That makes sense. https://github.com/hacketyhack/hacketyhack/blob/master/lib/art/turtle.rb

**Comment by noahgibbs** [comment]
When checked with the scarpe_widget branch so we have Shoes::Widget, the next incompatibility is the lack of a "window" method. That's also going to be a problem because window effectively creates a second Shoes::App object. So multi-app/multi-window is the next obstacle to running Hackety-Hack.

**Comment by noahgibbs** [comment]
Moved to Feature Brainstorming. This is far off. https://github.com/scarpe-team/scarpe/wiki/HacketyTrack.md
