### ISSUE TITLE
The Ultimate "Good First Issue"

### ISSUE THREAD

**Issue by Schwad** [scarpe-team/scarpe#173]
## Background

[Full context in thread on discord](https://discord.com/channels/1072538177321058377/1091676889376112700) <--

We had many, many issues in February

They anticipated defining every little bit of API

And tracking it.

We soon realized this would not be robust or maintainable for a healthy project or for contributors. 

So, we removed many of these issues, and adjusted our metric towards _example-driven-development_. 

We (at time of writing) have 256 Shoes examples. Our goal right now is to, one at a time, pass these examples in the Webview Display Service. If you want to explore or work on an alternative display service, you also want to pass these examples separately.

## What we need you to do

Pick up an example, make the changes need to pass it, make a PR, move the example into the working directory. Update the working example count [here in the README](https://github.com/scarpe-team/scarpe#are-we-done-yet).

That is the primary work! Secondary or other things can be filed as individual issues. 

## Why this matters

This, and the [Hackety Track issue](https://github.com/scarpe-team/scarpe/issues/166) are the two primary things we need to achieve to share this with the world.

**Comment by gintama91** [comment]
that is pointing towards wrong link ([Full context in thread on discord](https://github.com/scarpe-team/scarpe#are-we-done-yet) <--) should be updated to (https://discord.com/channels/1072538177321058377/1091676889376112700)

**Comment by Schwad** [comment]
thanks @gintama91 , nice catch!

**Comment by kartikeysharma98281** [comment]
Hi @Schwad, Can you please assign me this issue?

**Comment by Schwad** [comment]
Sure! I'll say for folks coming by, this issue can be worked by as many folks as you like

**Comment by sapienfrom2000s** [comment]
@gintama91 How can I access the discord group? Is it public?

**Comment by noahgibbs** [comment]
At this point, this is out of date. I'm replacing it with a [section in the wiki](https://github.com/scarpe-team/scarpe/wiki#contributing).
