### ISSUE TITLE
[Secondary DSL] Built-in dependencies

### ISSUE THREAD

**Issue by Schwad** [scarpe-team/scarpe#18]
These came with shoes. `binject` may not be necessary because I think that was for future package generation.

### Tasklist
  - Documented [here](https://github.com/shoes/shoes-deprecated/wiki/A-Developer%27s-Tour-Through-Shoes)
  - We may be able to treat these like runtime dependencies _for now_. But if we explore more packaging this up we may need to vendor these directly ala [here](https://github.com/shoes/shoes-deprecated/tree/develop/req).
  - [ ] binject, one-click installer
  - [x] [bloopsaphone, supports audio and chiptunes](https://github.com/whymirror/bloopsaphone)
  - [ ] chipmunk, [chipmunk physics support](https://github.com/ashbb/shoes_hack_note/blob/master/md/hack029.md)
  - [ ] ftsearch
  - [ ] Nokogiri, HTML parsing
  - [x] JSON
  - [ ] sqlite3, simple database support

**Comment by noahgibbs** [comment]
These days JSON is built into Ruby, so I'm checking it off.
