### ISSUE TITLE
Consider Syntax Tree for autoformatter

### ISSUE THREAD

**Issue by Schwad** [scarpe-team/scarpe#188]
Conversation here: https://github.com/scarpe-team/scarpe/pull/183#issuecomment-1566946786

It might be good to leverage SyntaxTree for our formatting needs, though I've known about it forever I've never integrated into an editor or setup! (because I have a slightly different setup for my day job)

I may be misremembering but it's worth exploring

**Comment by noahgibbs** [comment]
Is the idea that we'd use it to build our own Ruby formatter?

I'm assuming you mean this one: https://github.com/ruby-syntax-tree/syntax_tree

**Comment by noahgibbs** [comment]
Do you know if stree format is routinely used for IDEs? They mention that "stree check" is routinely used for CI to reject files where it doesn't like the formatting, which isn't quite the same thing.

I'm a little worried about it messing up fairly trivial things like multiline comments. I would assume that if it has problems that immediate and obvious, that it's not really designed for our use case. But maybe "stree format" is just the wrong part of syntax_tree?

**Comment by Schwad** [comment]
I know rbates likes it and that's what tempted me. Not to mention knowing the author 😂 

https://twitter.com/rbates/status/1643322846863855616?s=46&t=AQrrcgsggE7Z5MKkdH1lTg

**Comment by noahgibbs** [comment]
At this point, I feel like nobody's really messing with autoformatter stuff (I'm not particularly tempted to, personally.)

So my gut feel would be to close this. Any objections?
