### ISSUE TITLE
Change how SCARPE_DISPLAY_SERVICES works

### ISSUE THREAD

**Issue by noahgibbs** [scarpe-team/scarpe#193]
Right now, SCARPE_DISPLAY_SERVICES is a list of names of display service classes. There's a lot wrong with that.

It would be nice to include some type of shorter nickname(s) -- wv for webview, glibui for GlimmerLibUI, things like that. It would be nice to not load display services that aren't being used (though separating them into gems would fix that.) Right now that's hard, though, because you have to load the files to find the class names, which means you have to load all display services to know for sure *what* classes are there.

Switching to nicknames that match the require and directory name would be an improvement.

**Comment by Schwad** [comment]
> Switching to nicknames that match the require and directory name would be an improvement.

and it's okay if we intentionally obfuscate with cool nicknames. it's bad coding practice but I'm okay if we call webview "steve" and libui "horatio"

sorry, that's terrible. I shouldn't have proposed that. I take it back. 

but yes this makes sense. I haven't played with doing more than one. is the theory that it'd spit out two windows and we could compare?

**Comment by noahgibbs** [comment]
That's the theory. The longer we do this, the more I realise that's a bad idea. For instance, at some point we're going to want to be able to have Ruby code query what things are visible, exactly how large they turned out to be, etc. And having multiple answers to that is a bad idea.

The nickname thing is a good idea in any case - we do *not* want to name the display lib by a class name that Scarpe has to parse Ruby files to find. Instead we should use the name of the top require-able file -- so right now that would be wv, libui, glibui. And then Scarpe can just require it.

So if you wanted to name libui steve or horatio, you'd just need to ship a steve.rb or horatio.rb for them.

**Comment by noahgibbs** [comment]
This is related to #202 - we want to require there be one, and only one, display service at once.
