### ISSUE TITLE
0.2.0 Release

### ISSUE THREAD

**Issue by Schwad** [scarpe-team/scarpe#198]
- [ ] Ensure executable (ala `scarpe my_app.rb`)
- [ ] Cut Github release
- [ ] Create CHANGELOG with a bunch of what we've done, and also an 'unreleased' section
- [ ] Come up with a name (see discord)
- [ ] Publish to Rubygems

**Comment by noahgibbs** [comment]
At this point I think this is done. @schwad, agree or no?

**Comment by noahgibbs** [comment]
Okay, 0.2.1 is already released, closing this.
