### ISSUE TITLE
Hackdays prep wishlist

### ISSUE THREAD

**Issue by noahgibbs** [scarpe-team/scarpe#236]
This is the list of stuff I'd really like to get done before Hack Days, so that we're in relatively good shape to add a bunch of new people.

* <s>#232 - get destroy and heartbeat events sorted out so they're in a stable place; generally lock down the scarpe/display-service API pretty well</s> Fixed by #239 
* #229 - <s>find the source of the current CI instability and kill it with fire; maybe get resends working on JS evals</s> Tentatively fixed. I'll watch to see if I believe it.
* #198 - cut a release
* <s>Add a dependency on a forked Bloopsaphone that works with Ruby 3.2.0+ or figure out why that's not reasonable</s> Looks like bloops-0.5.0 works fine.

Whatever Hack Days project we choose is going to come with additional requirements (e.g. LibUI would require getting scarpe-folio updated, sound would mean figuring out basic sound output.)

**Comment by Schwad** [comment]
Yeah definitely ++ on the release; then the outcome of hackdays could be a 0.2.1! (Or higher if we go really breaking)

**Comment by noahgibbs** [comment]
Now that we know what we're doing for Hack Days, we probably want to add a priority item for some kind of audio interface. I'm adding it above, though I'm open to changing exactly what we're doing here.

**Comment by noahgibbs** [comment]
Okay, everything except the release is good to go, and the release has a separate issue. I'm closing this now.
