### ISSUE TITLE
support `border` for top-level document root

### ISSUE THREAD

**Issue by Schwad** [scarpe-team/scarpe#250]
## We should be able to cast border at the top level

Realistically, most all flow dsl should be available at the top.

### example case to pass

```ruby
Shoes.app title: "Cookies Recipe", height: 1000, width: 1000 do
  background "black"
  border "red", strokewidth: 10 # fails
  @header = banner "You've downloaded a virus!", :align => "center", :stroke => red
end
```

**Comment by noahgibbs** [comment]
I remember reading that in Shoes, border is a geometry, not a style. So we may want to handle it that way eventually.

Basically, make it literally a hollow box that can contain other stuff, kind of like a stack or flow.

**Comment by noahgibbs** [comment]
The Shoes app above runs fine these days. Closing.
