### ISSUE TITLE
Exploring stacks and flows

### ISSUE THREAD

**Issue by Schwad** [scarpe-team/scarpe#251]
## Example:

```ruby
Shoes.app title: "Cookies Recipe", height: 1000, width: 1000 do
  background "black"
  @header = banner "You've downloaded a virus!", align: "center", stroke: red

  flow do
    stack width: "100%" do
      background "white"
      title "You thought this was a recipe for cookies, but it was me, your arch nemesis!", align: "center"
      para "I have taken over your computer and will not give it back until you pay me $1,000,000.",
        align: "center",
        size: 30
    end
  end

  # flow do
  #   border "red", strokewidth: 10
  #   background "black"
  #   stack width: "33%" do
  #     background "green"
  #   end
  #   stack width: "33%" do
  #     background "white"
  #   end
  #   stack width: "33%" do
  #     background "red"
  #   end
  # end
end
```

Renders:

<img width="998" alt="image" src="https://github.com/scarpe-team/scarpe/assets/7865030/1f5982c5-c909-4411-a623-c73cc8637c1f">

## Example:

```ruby
Shoes.app title: "Cookies Recipe", height: 1000, width: 1000 do
  background "black"
  @header = banner "You've downloaded a virus!", align: "center", stroke: red

  # flow do
  #   stack width: "100%" do
  #     background "white"
  #     title "You thought this was a recipe for cookies, but it was me, your arch nemesis!", align: "center"
  #     para "I have taken over your computer and will not give it back until you pay me $1,000,000.",
  #       align: "center",
  #       size: 30
  #   end
  # end

  flow do
    border "red", strokewidth: 10
    background "black"
    stack width: "33%" do
      background "green"
    end
    stack width: "33%" do
      background "white"
    end
    stack width: "33%" do
      background "red"
    end
  end
end
```

Renders:

<img width="995" alt="image" src="https://github.com/scarpe-team/scarpe/assets/7865030/ac978fba-e146-4b0f-8609-5840e0f66f06">

## Together....

<img width="1001" alt="image" src="https://github.com/scarpe-team/scarpe/assets/7865030/4c25e6ad-40ca-4e92-8c9b-99b08390dc27">

## My thoughts

I'm happy to be corrected if I'm missing something here. But we really want this application to be resilient to lots of stacks and flows!

**Comment by Schwad** [comment]
OR maybe I need to be more aggressive with specifying flow heights!

I wonder if flows should default to sharing an equal share of the remaining height. but we'll specify for now

**Comment by Schwad** [comment]
Though I do think the shoes-ism of stacks over 100% spilling to the bottom may not be happening:

here the second stack doesn't show

```ruby
  flow height: "30%" do
    stack width: "100%" do
      background "white"
      title "You thought this was a recipe for cookies, but it was me, your arch nemesis!", align: "center"
      para "I have taken over your computer and will not give it back until you pay me $1,000,000.",
        align: "center",
        size: 30
    end
    stack width: "100%" do
      para "Pay me now or I will delete all your files!"
    end
  end
```

**Comment by noahgibbs** [comment]
Something that would be useful where you can: if you can try it in Shoes3 and show us what it does, we can try to match it.

But there are definitely gonna be a lot of funky layout problems before we're done :-)

**Comment by noahgibbs** [comment]
Okay, I feel like this is mostly sorted out and the rest is in issue #273. Do you agree?

**Comment by noahgibbs** [comment]
At this point, other than some of the border/padding stuff (and a few sizes), this works. Closing.
