### ISSUE TITLE
If I were just curious

### ISSUE THREAD

**Issue by Schwad** [scarpe-team/scarpe#252]
In a web app I could just point to a bootstrap CDN and goof around with styles quickly.

If I wanted to do a local experiment with the in webview, where would I go? 🤔

**Comment by noahgibbs** [comment]
So you mean, like, live update? We don't currently have anything like that, but it's a thing that could be built. We'd need to reload the Ruby file, basically. Which would potentially be a problem for some Shoes apps, but many could probably handle it just fine.

**Comment by Schwad** [comment]
I just mean using the bootstrap library in my html. 

I know that would require writing new widgets that probably inherit from button and para and whatnot. 

stack "col-md-3" could be cool

**Comment by noahgibbs** [comment]
Yeah, you could definitely do interesting layout with an HTML grid system...

**Comment by noahgibbs** [comment]
You can find the Bootstrap CDN code here: https://getbootstrap.com/docs/3.3/getting-started/

That link should work just fine in Webview.
