### ISSUE TITLE
`scarpe schwad party_time`

### ISSUE THREAD

**Issue by Schwad** [scarpe-team/scarpe#275]
Would be great to have remote shoes apps immediately available by user name and app name

Gists don't quite work because they aren't named: e.g. https://gist.github.com/Schwad/6e618072c0fdb6914e53f55f06676546

I'm just thinking how neat it would be to tell someone about scarpe and they could use it like

`gem install scarpe`
`scarpe schwad party_time`

and be done

**Comment by noahgibbs** [comment]
We could do something along those lines. I'd prefer to have *some* command name, but something like:

"scarpe party schwad gogo", where "party" is the subcommand.

Or "scarpe_party schwad gogo"? But from something like that, we could download a manifest from a named GitHub repo or something along those lines.

**Comment by Schwad** [comment]
Yeah we could absorb the responsibility of a curated list of apps etc

A registry

A shoes store!

**Comment by noahgibbs** [comment]
We could. I'd suggest either "ID plus name gives GitHub repo, check that repo for manifest at a known path" or "big central manifest, check that."

**Comment by noahgibbs** [comment]
Moving this to Feature Brainstorming in the wiki since I don't think anybody is working on it short-term: https://github.com/scarpe-team/scarpe/wiki/ScarpeParty.md
