### ISSUE TITLE
Prototype better shape/mask support

### ISSUE THREAD

**Issue by noahgibbs** [scarpe-team/scarpe#284]
Shoes has a bunch of shapes - line, arc, oval, etc. Its other shapes (e.g. image, para) can also be treated as shapes for what I'm about to mention.

Shoes has a "shape do" block that is basically a union type -- put all the mentioned shapes together into one. For fill and stroke, it's supposed to treat them as one lump. So, like, an oval plus  rectangle could turn into a round-topped tall rectangle if you put them in the right places. That sounds easy with fill (draw the two of them, call it a day) but of course stroke -- the outside outline of a round-topped rectangle -- is a harder problem.

Shoes also has a "mask do" block, which lets you use one chunk of geometry as a sort of filter or stencil for other stuff. Like, if you had a "mask do" with an oval inside, Shoes is only supposed to draw all the other stuff in that slot *inside* the oval. It doesn't draw the oval, but the oval acts like a stencil, cutting away everything that isn't in the oval.

So here's a thing: that means oval does a different thing in one place than another. With no shape or mask, it draws an oval, pretty much like we see now in Scarpe. Inside a mask block, the oval is added to the mask. In a slot that *has* a mask block, the oval is drawn with the mask applied. Inside a shape block, the oval is unioned with other shapes if there are any, probably to get calculated by something before it's drawn.

So that means we need a drawing mode somewhere so that a shape knows what it should be doing.

I suspect to_html is going to have to grow a drawing context of some kind. We're already seeing interesting situations with basic stuff like fill and stroke. Drawing mode is a bigger thing of the same kind. So a drawing context parameter to to_html is probably the answer.

This issue is to prototype the basic context-passing and multiple drawing modes. There's going to be a *lot* of fine-tuning here.

Mask can be done using [the css mask property](https://developer.mozilla.org/en-US/docs/Web/CSS/mask) maybe, where all the shapes are drawn into an SVG mask and then the mask is applied by CSS. But there are a lot of issues with getting what I just said to actually work right (do we need to duplicate how we do CSS padding, but with SVG shapes?).

Union shapes are [also probably possible](https://stackoverflow.com/questions/39193276/how-can-i-merge-two-shapes-in-svg), and also kind of subtle. You can make the same kind of union mask thing, and then just use it to cut a shape out of a rectangle. Would that handle stroke correctly? Don't know, but we could find out.

**Comment by gintama91** [comment]
does changing to canvas frm svg makes this any better?

**Comment by gintama91** [comment]
on events such as star.move left top and all ig we need more preciison abt pixels? svg is bit weird here

**Comment by gintama91** [comment]
or maybe i did smthng wrng too.

**Comment by noahgibbs** [comment]
Looks like canvas has globalCompositeOperation, which could help with the union shapes. So yeah, canvas could help that way. We'd need to basically write a layout engine in canvas to make it work. Not sure if we'll be doing that regardless.

As far as more precision, it shouldn't be hard to get that with svg. You're allowed to define an svg-specific coordinate system, for instance, and I'm pretty sure you can use float coordinates. But maybe I'm not understanding what you want.

**Comment by noahgibbs** [comment]
This is feature brainstorming, not really an issue. Moving to https://github.com/scarpe-team/scarpe/wiki/ShapesAndMasks.md
