### ISSUE TITLE
Lacci: what name for command line utility?

### ISSUE THREAD

**Issue by noahgibbs** [scarpe-team/scarpe#346]
In Shoes4, with shoes-core, they have a "shoes" command which selects a backend and runs it. That makes sense.

We could literally just use "shoes" as our backend command, though I'm a little worried about conflicts - Shoes4 definitely has a "shoes" command and Shoes3 kinda-sorta has one, at least on Mac. I can't tell if it would ever wind up in the path.

We could also use 'lacci', but that seems pretty unexpected. Nothing else the user directly interacts with is named 'Lacci' -- that's normally a behind-the-scenes name. Of course, increasingly so is Scarpe, and Scarpe is kind of all mixed up with Scarpe-Webview.

Shoes3 also seems to have a shoes-launch command, so we could steal that name. Or come up with something similar of our own, based on the idea that we're running a Shoes app.

But the Scarpe command, used for Scarpe Webview apps, should probably become like scarpe-folio's "folio" command (https://github.com/scarpe-team/scarpe-folio/blob/main/exe/folio), just setting a default display lib and handing off to a display-lib-neutral launcher. That would also let us do Webview-specific stuff (e.g. print Webview-based env vars) in a way that non-web-based display libs didn't automatically inherit.

**Comment by Schwad** [comment]
I think this is a good question. and I agree with the thought about lacci.

I'd love to keep command utility names as `scarpe`-based *for now*... but when I think about it when you run truffleruby you're still running the 'ruby' command right? so maybe that could be our north start for long-term also taking over the shoes command namespace as well. though I could see separation being handy selfishly for our development where we might be running several different shoes setups locally to test them too.

**Comment by noahgibbs** [comment]
As far as distinguishing multiple Scarpe versions in dev, I think eventually we'll wind up with the Scarpe Webview gem completely extracted. And at that point, dev setup becomes "clone a repo for each variation of Scarpe, it's fine if some of them are just branches of each other, and run ./exe/scarpe --dev in the repo you want to use." You'll be running it in the display-lib-specific repo, not the lacci or core scarpe repo.

"Core scarpe repo?" Yeah, we're gonna wind up with things like logging and HTML rendering and unit testing that aren't display-lib-specific, but belong in a more generic Scarpe repo. It's a lot of what's in lib/scarpe but not lib/scarpe/wv and doesn't have wv in the name. It will expand over time.

But you probably mean shoes3 vs shoes4 vs scarpe. That's certainly fair. And we probably don't want to cause problems for any user who tries to install both gems, because Shoes users are some of the users we care about *most*. So that's an argument in favour of not just taking "shoes" as a name to avoid conflicts.

We could still have a shoes-run or something that is clearly about shoes but doesn't conflict with an existing shoes3 or shoes4 binary.
