### ISSUE TITLE
Why does ListBox have both selected_item and choose as styles?

### ISSUE THREAD

**Issue by noahgibbs** [scarpe-team/scarpe#432]
It seems like at least one would be redundant. Remove one if possible, or document the difference if we actually need both.

**Comment by gintama91** [comment]
hm. i think choose is for choosing certain element as default while loading , selected_item is to render what user selected after listbox is initially rendered?

**Comment by noahgibbs** [comment]
Ah, looks like "selected_item" isn't in original Shoes -- there it's always "choose". Cool, we should get rid of selected_item then.

Looks like choose: can be specified to the constructor to set the initially-chosen item, like we do. And list_box.choose("item") is supposed to also work (we don't do that yet.) And then they use .text to get the text of the chosen value.

**Comment by noahgibbs** [comment]
Fixed in #442.
