### ISSUE TITLE
Inconsistent naming of Shoes errors

### ISSUE THREAD

**Issue by noahgibbs** [scarpe-team/scarpe#474]
The word "Error" is at the end of most shoes errors... but not UnregisteredShoesEvent. We go back and forth between NoSuchStyleError, NoSuchItemListError and NoLinkableIdError (instead of NoSuchLinkableIdError.)

The ones that don't match should have their names fixed in lacci/lib/shoes/errors.rb, but also where the errors can be thrown.

**Comment by Nj221102** [comment]
Hi, @noahgibbs  

In this issue, I should 
 1.⁠ ⁠change every error name that doesn’t end with a word error 
 2.⁠ ⁠⁠merge NoSuchStyleError, NoSuchItemListError and NoLinkableIdError into a single error called NoSuchLinkableIdError.

Am I correct

**Comment by noahgibbs** [comment]
You're right about point 1. For point 2, no. In this case we have three errors for "something wasn't found." Two are NoSuchWhateverError while the third is NoWhateverError.

So either NoLinkableIdError should be NoSuchLinkableIdError, or the word "Such" should be removed from the other two.

**Comment by Nj221102** [comment]
> You're right about point 1. For point 2, no. In this case we have three errors for "something wasn't found." Two are NoSuchWhateverError while the third is NoWhateverError.
> 
> So either NoLinkableIdError should be NoSuchLinkableIdError, or the word "Such" should be removed from the other two.

thanks, will start working on it.
