### ISSUE TITLE
Add Shoes3 as to helper development command

### ISSUE THREAD

**Issue by CalvinWalzel** [scarpe-team/scarpe#50]
Just an idea:

Maybe we could add Shoes3 as a dev dependency and add a flag to the helper development command (`/exe/scarpe`) so it runs an example both with Scarpe & Shoes3. Makes it easier to compare if we've reached (visual/UX) parity in an example.

What do others think of this?

**Comment by noahgibbs** [comment]
I don't think this gains us much over writing a tiny little shellscript to do this individually. I don't think this is a common part of our workflow. Unless anybody objects, I'll close this issue.
