### ISSUE TITLE
[Research] Replace web_view with Chromium

### ISSUE THREAD

**Issue by CalvinWalzel** [scarpe-team/scarpe#96]
Briefly discussed during a call today:

It might be interesting to look into replacing web_view with Chromium. This way scarpe apps would behave exactly the same on all operating systems and it would be easier to implement proper (headless) testing using for example puppeteer.

Link to investigate: [CEF (Chromium Embedded Framework)](https://bitbucket.org/chromiumembedded/cef/src/master/)

**Comment by Schwad** [comment]
There's a discussion going on in #general on the discord, so the context isn't lost, one thing floated as well via @noahgibbs is the _idea_ of having a swappable backend... So on an `env['CI'] == true` we could grab chromium instead from webwrangler

**Comment by noahgibbs** [comment]
Oh hey, I just realised we'd need a way to patch our Ruby into Chromium. So this would be a *ton* of work, far more than we've put into Scarpe so far.

**Comment by noahgibbs** [comment]
Hm, or not. Okay, so, one way we could make Chromium work is that we could just have an array, sitting around as something like 'window.rpc_calls', of Ruby events. And all our current "call to Ruby" bindings would become "serialise your args to JS, and leave an rpc_calls entry".

We'd lose immediate notification - no way to just call straight into Ruby immediately and synchronously. And the JS direction would need to wait for the JS event loop to be free, just like it is now, but it would gain the ability to return values reliably.

Here's an example of the Puppeteer (Chrome/Chromium DevTools protocol) ported to Ruby: https://github.com/YusukeIwaki/puppeteer-ruby

So we'd basically need to poll continuously from Ruby, looking for entries in that array and then dispatching them to Ruby handlers.

**Comment by noahgibbs** [comment]
What I like about a Puppeteer-type infrastructure is that it gets rid of a bunch of our Ruby-side limitations. Puppeteer-ruby launches Chrome as a separate process (https://github.com/YusukeIwaki/puppeteer-ruby/blob/main/lib/puppeteer/launcher/chrome.rb), so no more segfaults from injecting weird C code into the browser process. And the relatively 'hands-off' RPC would make it easier to avoid Ruby-caused crashes (e.g. add a 1-second sleep to an event in your Shoes app, JS event loop stalls, chaos ensues even *after* we find and fix the current segfault that happens.)

Of course, we'd also be managing another process, which means cleanup issues. Leaving old copies of Chrome running is a bad thing in all sorts of ways. We'd need to do things like look for stale copies on startup and kill them, and keep a fairly robust "oh hey we got an exception, let's make sure the browser process is dead" routine. Chrome is *big*.

**Comment by CalvinWalzel** [comment]
Looks like the ruby port doesn't support all features of puppeteer yet: [API coverage](https://github.com/YusukeIwaki/puppeteer-ruby/blob/main/docs/api_coverage.md)

**Comment by noahgibbs** [comment]
Yup. I think it would adequate for our usage, but rough around the edges, rather like webview.

**Comment by noahgibbs** [comment]
The current work to separate the Shoes layer from the Webview layer should make this a lot more doable. https://github.com/scarpe-team/scarpe/pull/118

**Comment by noahgibbs** [comment]
Okay, this hasn't been looked at in awhile. And it would basically be a whole new display service, and not a particularly small one. I think we can close this issue until/unless somebody gets serious about writing this.
